server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
      
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest  
    
  data:
    mongodb:
      uri: mongodb://192.168.99.100:32768/testdb
      
  cloud:
    stream:
      bindings:
        input:
          destination: advertise
          
