server:
  port: 8080
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
      
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest        
    
  data:
    mongodb:
      uri: mongodb://192.168.99.100:32768/testdb
      
  cloud:
    stream:
      bindings:
        advertise: 
          destination: advertise
          content-type: application/x-spring-tuple
        subscribe:
          destination: subscribe
          
          
zuul:
  ignored-services: '*'    
  routes:
    advertise: 
      path: /job/**
      service-id: advertise-service      
    subscribe:
      path: /subscribe/**
      service-id: subscribe-service

feign:
  compression:
    request: 
      enabled: true
    response:
      enabled: true
