server:
  port: 9999
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.100:32768/testdb
      
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        input:
          destination: oauth2
